---
title: "Nutzung von GeoDaten in den Sozialwissenschaften - Zufallszahlen"
author: "Jan-Philipp Kolb"
date: "08 April 2016"
output:
  slidy_presentation:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Erzeugung von ganzzahligen Zufallszahlen

```{r}
Asample <- sample(1:5,1000,replace=T)
head(Asample)
table(Asample)
```

## Gleichverteilte Zufallszahlen

```{r,eval=F}
A <- runif(100)
head(A)
hist(A)
```

## Gleichverteilte Zufallszahlen in einem Rahmen

```{r,eval=F}
A2 <- runif(100,100,200)
head(A2)
hist(A2)
```

## Normalverteilte Zufallszahlen

```{r}
Bnrom <- rnorm(1000)
hist(Bnrom,col="royalblue")
```

## Normalverteilte Zufallszahlen

```{r,eval=F}
?rnorm
```


```{r}
Bnrom2 <- rnorm(1000,mean=-100,sd=20)
hist(Bnrom2,col="red")
```

## Das Runden

Zahlen runden:

```{r}
(A <- rnorm(10))
```

```{r}
round(A)
```

```{r}
round(A,digits=2)
```

## R als Taschenrechner

```{r}
2/4
```

```{r}
2*4
```

```{r}
sqrt(5)
```

## Ein Kreisdiagramm

```{r}
Students <- c(100, 200,30)
pie(Students)
```

## Graphiken speichern

```{r}
pdf("pie_Students.pdf")
pie(Students)
dev.off()
```
