---
title: "Datahub"
author: "Jan-Philipp Kolb"
date: "24 Februar 2016"
output: slidy_presentation
---


```{r,echo=F}
library(knitr)
Ex <- F
```


## Datenquellen

- Auf dem Portal [datahub.io](http://datahub.io/) sind sehr viele Beispieldatensätze in verschiedenen Formaten abrufbar. 

You can download a statistic on dead refugees from [unitedagainstracism.org](unitedagainstracism.org)

[Link datahub.io](http://datahub.io/dataset/list-of-deaths-on-the-borders-of-europe-1993-2012/resource/cc85b8fc-99be-4503-9040-099ee3a42efd)

```{r,echo=F,eval=Ex}
data.path <- "J:/Work/Statistik/Kolb/Workshops/2015/Spatial_MA/Folien/dataImport/data"
setwd(data.path)
load("listofdeath_small.Rdata")
```


```{r,eval=F}
data.path <- "C:/Work/data/"
setwd(data.path)
lod <- read.csv("listofdeath.csv")
```


```{r}
link <- "https://raw.github.com/mihi-tr/list-of-deaths-dpkg/master/data/listofdeath.csv"

lod <- read.csv(link)
```

```{r}
kable(lod)
```


## UNESCO Weltkulturerbe

Unesco world heritage sites:
[Link datahub.io](http://datahub.io/dataset/unesco-world-heritage-sites/resource/d4116195-44d8-4bc1-9f91-9b570870dc19)

```{r,echo=F,cache=T,eval=F}
setwd("J:/Work/Statistik/Kolb/Workshops/2015/Spatial_MA/Folien/dataImport/data")
load("whc.RData")
```


## Links

Roger Bivand - [Spatial Analysis of SIDS data](https://datahub.io/dataset/sudden-infant-death-syndrome/resource/b456a0ea-fa2c-4809-b2d2-fe109ecdf83e)

[FAOSTAT and WDI](https://cran.r-project.org/web/packages/FAOSTAT/vignettes/FAOSTAT.pdf)
