---
title: "Intro in Using Databases with R"
author: "Jan-Philipp Kolb"
date: "Tue Mar 01 08:38:40 2016"
output: html_document
---



## [Getting Started](https://datashenanigan.wordpress.com/2015/05/18/getting-started-with-postgresql-in-r/)

PostgreSQL has the advantage of being open source 

- [Download PostreSQL](http://www.postgresql.org/download/windows/)
- Start pgAdmin III
- To connect to the database double click on the server in pgAdmin III

- [Set up a new user](https://doc.odoo.com/install/windows/postgres/)

## Connect with R

```{r,eval=F}
require("RPostgreSQL")
# create a connection
# save the password that we can "hide" it as best as we can by collapsing it
pw <- {
  "new_user_password"
}
 
# loads the PostgreSQL driver
drv <- dbDriver("PostgreSQL")
# creates a connection to the postgres database
# note that "con" will be used later in each connection to the database
con <- dbConnect(drv, dbname = "cartable",
                 host = "localhost", port = 5432,
                 user = "postgres", password = pw)
rm(pw) # removes the password
 
# check for the cartable
dbExistsTable(con, "tab1")
# TRUE
```

## Use OpenStreetMap data

```{r,eval=F}
generator <- read.csv("https://raw.githubusercontent.com/Japhilko/GeoData/master/data/Deutschland_generator.csv")
```




## Write and Load

```{r,eval=F}
data(mtcars)
df <- data.frame(generator, 
                 row.names = NULL)

# writes df to the PostgreSQL database "postgres", table "cartable" 
dbWriteTable(con, "tab1", 
             value = df, append = TRUE, row.names = FALSE)
 
# query the data from postgreSQL 
df_postgres <- dbGetQuery(con, "SELECT * from cartable")
 
# compares the two data.frames
identical(df, df_postgres)
# TRUE
 
# Basic Graph of the Data
require(ggplot2)
ggplot(df_postgres, aes(x = as.factor(cyl), y = mpg, fill = as.factor(cyl))) + 
  geom_boxplot() + theme_bw()
```

