---
title: "Course 6"
author: "Jan-Philipp Kolb"
date: "Wed Oct 21 12:57:49 2015"
output: md_document
---

```{r,echo=F}
library(knitr)
```


## Datasets

```{r,echo=F}
Toppics <- c("London Soccer","World Heritage Sites","Nursery Data","Backpacker","Economic Crisis","Camping")
DataSet <- c("Lfb_df.csv","whcSites.csv","df_pflege.csv","Hostels_Madrid.csv","Unemployment.csv","CampSites_Bayern.csv")

topics_df <- data.frame(Toppics,DataSet)
kable(topics_df)
```

## London Soccer

You can find the data [here](https://github.com/Japhilko/GeoData/tree/master/2015/data)

```{r soccer data,cache=T}
url <- "https://raw.githubusercontent.com/Japhilko/
GeoData/master/2015/data/Lfb_df.csv"

Lfb_df <- read.csv(url) 
```

## Overview Data - London soccer

```{r,echo=F}
kable(Lfb_df[1:8,1:4])
```

## World Heritage Sites

```{r whcSites,cache=T}
url <- "https://raw.githubusercontent.com/Japhilko/
GeoData/master/2015/data/whcSites.csv"

whcSites <- read.csv(url) 
```

## Overview Data - World Heritage

```{r,echo=F}
kable(whcSites[1:8,1:5])
```


## Nursery example


```{r}
url <- "https://raw.githubusercontent.com/Japhilko/
GeoData/master/2015/data/df_pflege.csv"

nursery <- read.csv(url) 
```


## Overview Data - Nursery

```{r,echo=F}
kable(nursery[1:8,1:5])
```


## Backpacker example


```{r}
url <- "https://raw.githubusercontent.com/Japhilko/
GeoData/master/2015/data/Hostels_Madrid.csv"

Hostels <- read.csv(url) 
```


## Overview Data - Hostels

```{r,echo=F}
kable(Hostels[1:8,1:4])
```


## Example - Economic crisis


```{r}
url <- "https://raw.githubusercontent.com/Japhilko/
GeoData/master/2015/data/Unemployment.csv"

Hostels <- read.csv(url) 
```


## Overview Data - Unemployment

```{r,echo=F}
kable(Hostels[1:8,1:4])
```


## Example - Camping


```{r}
url <- "https://raw.githubusercontent.com/Japhilko/
GeoData/master/2015/data/CampSites_Bayern.csv"

CampSites <- read.csv(url) 
```


## Overview Data - Camp Sites in Bayern

```{r,echo=F}
kable(CampSites[1:8,1:4])
```


