---
title: "Sources for polygons"
author: "Jan-Philipp Kolb"
date: "04/24/2015"
output: ioslides_presentation
---



```{r,echo=F}
library(knitr)
ca <- T
```

## [GADM](http://www.gadm.org/) - NUTS level 2

```{r,cache=ca,warning=F}
library(raster)
LUX2 <- getData('GADM', country='LUX', level=2)
plot(LUX2)
```

## [GADM](http://www.gadm.org/)- NUTS level 3

```{r,cache=ca,warning=F}
LUX3 <- getData('GADM', country='LUX', level=3)
plot(LUX3)
```

## [GADM](http://www.gadm.org/)- NUTS level 4

```{r,cache=ca,warning=F}
LUX4 <- getData('GADM', country='LUX', level=4)
plot(LUX4)
```

## [GADM](http://www.gadm.org/)- NUTS level 3

```{r,cache=ca,warning=F}
DEU3 <- getData('GADM', country='DEU', level=3)
plot(DEU3)
```


## Postal codes for Germany

<http://datahub.io/de/dataset/postal-codes-de>

```{r,cache=ca,warning=F}
setwd("D:/Daten/Daten/GeoDaten")
library(rgdal)
PLZ <- readOGR ("post_pl.shp","post_pl")
```

## Plot Mannheim

```{r,cache=ca,warning=F}
MA <- PLZ[PLZ@data$PLZORT99=="Mannheim",]
plot(MA)
#bbox4 <- bbox(MA)
```


## Source GeoData Germany

[Source GeoData Germany](http://www.geodatenzentrum.de/geodaten/gdz_rahmen.gdz_div?gdz_spr=deu&gdz_akt_zeile=5&gdz_anz_zeile=1&gdz_unt_zeile=14&gdz_user_id=0)

## Other sources

```{r,eval=F,echo=F}
git.path <- "C:/Users/kolbjp/Documents/GitHub/GeoData"
setwd(git.path)
library(mapdata)
```

## More sources

- [World Borders Dataset](http://thematicmapping.org/downloads/world_borders.php)
