---
title: "Use R-package osmar"
author: "Jan-Philipp Kolb"
date: "Thu Jun 11 17:13:33 2015"
output: ioslides_presentation
---

## Download information

```{r}
library(ggmap)
library(osmar)
api <- osmsource_api()
```

```{r}
cityC <- geocode("Mannheim Seckenheim")
bb <- center_bbox(cityC$lon,cityC$lat,1000, 1000)
ua <- get_osm(bb, source = api)
```

## What is inside:

You get three types of objects:

```{r}
names(ua)
```

## What is behind:

[Osmosis](http://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.44#--tag-filter_.28--tf.29) is a command line Java application for processing OSM data.

## Further tutorials on the usage of osmar and OpenStreetMap data:

- [OpenStreetMap2R with osmar](http://giswerk.org/doku.php?id=r:r-tutorials:packages:osmar#things_of_further_interest)

- [Using data from OpenStreetMap to map](https://github.com/Robinlovelace/osm-tutorial/blob/master/osm.Rmd)


- [Cookbook on using osmar](http://generalcookbook.blogspot.de/2013/08/application-of-openstreetmap-data-in.html?view=classic)

