---
title: "Use xapi"
author: "Jan-Philipp Kolb"
date: "12. Juni 2015"
output: html_document
---

```{r,eval=F,echo=F}
path <- "C:/Users/kolbjp/Documents/GitHub/GeoData/workshops"
setwd(path)
```



```{r}
library(XML)
```


## Download specific information

mapquest Xapi Service:

<http://open.mapquestapi.com/xapi/>


Organisation of bounding box:

[left,bottom,right,top]

for example Mannheim Seckenheim:

[8.5382,49.4573,8.5808,49.4759]

<http://open.mapquestapi.com/xapi/api/0.6/node%5Bamenity=pub%5D%5Bbbox=8.5382,49.4573,8.5808,49.4759%5D>

<http://open.mapquestapi.com/xapi/api/0.6/node%5Bamenity=pub%5D%5Bbbox=-77.041579,38.885851,-77.007247,38.900881%5D>

```{r}
ab <- xmlParse("http://open.mapquestapi.com/xapi/api/0.6/node%5Bamenity=pub%5D%5Bbbox=-77.041579,38.885851,-77.007247,38.900881%5D")

bbox <- "-77.041579,38.885851,-77.007247,38.900881"
abc <- xmlParse(paste("http://open.mapquestapi.com/xapi/api/0.6/node%5Bamenity=pub%5D%5Bbbox=",bbox,"%5D",sep=""))
```

Finding a specific place

```{r}
library(ggmap)
  # lon - east west
  # lat - south north
MAcode1 <- geocode("Mannheim Sandhofen")
MAcode2 <- geocode("Mannheim Rheinau")

MAcode3 <- geocode("Mannheim Schloss")
MAcode4 <- geocode("Mannheim Wallstadt")

  # [left,bottom,right,top]
bbox2 <- paste(MAcode3$lon,MAcode2$lat,MAcode4$lon,MAcode1$lat,sep=",")
abcd <- xmlParse(paste("http://open.mapquestapi.com/xapi/api/0.6/node%5Bamenity=pub%5D%5Bbbox=",bbox2,"%5D",sep=""))
```



```{r}
library(raster)
LUX3 <- getData('GADM', country='LUX', level=3)

LUXT <- LUX3[LUX3@data$NAME_3=="Troisvierges",]
```

```{r}
library(sp)
bLUXT <- bbox(LUXT)
bbox3 <- paste(bLUXT[1,1],bLUXT[2,1],bLUXT[1,2],bLUXT[2,2],sep=",")
abct <- xmlParse(paste("http://open.mapquestapi.com/xapi/api/0.6/node%5Bamenity=pub%5D%5Bbbox=",bbox3,"%5D",sep=""))
```



```{r}
?xmlToList
```



```{r}
abce <- xmlParse("http://open.mapquestapi.com/xapi/api/0.6/node[amenity=pub][bbox=8.41420088819042,49.467729452325514,8.551529989747436,49.517905125443455]")
```


## Links

<http://gis.stackexchange.com/questions/18124/how-do-i-download-specific-openstreetmap-data-by-tag>
