---
title: "Animated spatial visualisations"
author: "Jan-Philipp Kolb"
date: "24. April 2015"
output: ioslides_presentation
---

## Get the coordinates

```{r}
library(ggmap)
coords <- geocode("GESIS Mannheim")
```


## Get a scalable map

```{r,warning=F,message=F}
library(magrittr)
library(leaflet)
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=coords$lon, lat=coords$lat, popup="GESIS Mannheim")
m  # Print the map
```


## Links

- [The Map Widget](http://rstudio.github.io/leaflet/map_widget.html)

- [Radar and leaflet](http://www.r-bloggers.com/playing-with-leaflet-and-radar-locations/)


## 


```{r,message=F,eval=F}
library(googleVis)
setwd("C:/Users/kolbjp/Documents/GitHub/GeoData")
```



```{r,eval=F}
?gvisMap
M1 <- gvisMap(Andrew, "LatLong" , "Tip",
              options=list(showTip=TRUE, showLine=TRUE, enableScrollWheel=TRUE,
                           mapType='hybrid', useMapTypeControl=TRUE,
                           width=800,height=400))

plot(M1)
```


## R-package [RgoogleMaps](https://cran.r-project.org/web/packages/RgoogleMaps/index.html)

```{r,eval=Ex}
library(RgoogleMaps)
newmap <- GetMap(center = c(52.52001,13.40495), zoom = 14, 
                 destfile = "Berlin.png", 
                 maptype = "satellite")
PlotOnStaticMap(newmap)
?bubbleMap
```

## googleVis

```{r,eval=Ex}

library(googleVis)

data(Exports)    # a simple data frame
Geo <- gvisGeoMap(Exports, locationvar="Country", 
numvar="Profit",options=list(height=400, 
dataMode='regions'))
plot(Geo)
```

## plotting Andrew

```{r,eval=Ex}
data(Andrew)
M1 <- gvisMap(Andrew, "LatLong", "Tip", 
              options=list(showTip=TRUE, showLine=F, 
enableScrollWheel=TRUE, mapType='satellite', 
useMapTypeControl=TRUE, width=800,height=400))
plot(M1)
```

## More information

See [Here](http://pakillo.github.io/R-GIS-tutorial/#googlevis) for more information.

## rworldmap

```{r,eval=Ex}
library(rworldmap)
# different resolutions available
newmap <- getMap(resolution = "coarse")  
plot(newmap)
```

## Vignette

```{r,eval=Ex}
library(rworldmap)
vignette('rworldmap')
mapCountryData()
```

## Package dismo

[dismo](http://vijaybarve.files.wordpress.com/2012/07/dan_chr3.png)

```{r}
library(dismo)
mymap <- gmap("France")  # choose whatever country
plot(mymap)
```

